identity = "~/.config/solana/id.json"
rpc_url = "http://localhost:8899"

[[collections]]
name = "pay-with-send-token"
address = "127.0.0.1"
port = 3000
protocol = "http"

[[collections]]
name = "kmno-staking"
address = "127.0.0.1"
port = 3001
protocol = "http"

[[collections]]
name = "create-squads-multisig"
address = "127.0.0.1"
port = 3002
protocol = "http"
