identity = "~/.config/solana/id.json"
rpc_url = "https://mainnet.helius-rpc.com/?api-key=22a5a327-77fd-4021-b6d3-2d1ccb26fb18"

[[collections]]
name = "pay-with-send-token"
address = "127.0.0.1"
port = 3000
protocol = "http"

[[collections]]
name = "kmno-staking"
address = "127.0.0.1"
port = 3001
protocol = "http"
