[package]
name = "kmno-staking"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
bincode = "1.3.3"
serde = "1.0.209"
sha2 = "0.10.8"
solana-sdk = "2.0.7"
spl-associated-token-account = "4.0.0"
spl-token = "6.0.0"
znap = "0.1.36"
