[package]
name = "create-squads-multisig"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
bincode = "1.3.3"
borsh = "1.5.1"
serde = "1.0.209"
serde_json = "1.0.127"
sha2 = "0.10.8"
solana-sdk = "2.0.8"
spl-associated-token-account = "5.0.0"
spl-token = "6.0.0"
znap = "0.1.37"
